on:
  push:
    branches:
      - main
      - master

name: build-site

jobs:
  build-site:
    runs-on: ubuntu-18.04
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/bionic/latest
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        id: install-r

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'

      - name: Compile exercises
        run: bash compile_exercises.sh

      - name: Build website
        run: |
          Rscript -e 'rmarkdown::render_site()'
          touch _site/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: _site
          single-commit: true
